project:
  type: website
resources:
  - RyanToloneResume.pdf

website:
  title: "Ryan Tolone"
  description: "Ryan Tolone is a 3rd year statistics and data scientist at UCLA working on AI and ML"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects
        text: Projects
      - href: blog
        text: Blog
    right:
      - text: Resume
        href: RyanToloneResume.pdf

  page-footer:
    left: "(c) Ryan Tolone, 2025–. [Disclaimer](disclaimer)"
  open-graph: true

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center



